FROM redbitcz/wkpdf:8.0

LABEL org.label-schema.name="PHP 8.0 (Apache module + XDebug), Debian Buster"

# Configure Xdebug
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

# Prevent interactive block
ARG DEBIAN_FRONTEND=noninteractive

# Install Xdebug
RUN set -eux; \
    pecl install xdebug; \
    pecl clear-cache; \
    docker-php-ext-enable xdebug; \
    rm -rf /var/tmp/* /tmp/*;
